version: '3'

services:
  # Backend service
  backend:
    build: ./backend
    ports:
      - "5000:5000" # Exposing the backend on port 5000
    env_file:
      - .env.docker # Pointing to the new .env.docker file for Docker use
    depends_on:
      - mongo # Ensures MongoDB starts before the backend

  # Frontend service
  frontend:
    build: ./frontend
    ports:
      - "3000:3000" # Exposing the frontend on port 3000
    depends_on:
      - backend # Ensures the backend starts before the frontend

  # MongoDB service
  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017" # Exposing MongoDB on its default port
    volumes:
      - mongo-data:/data/db # Persisting MongoDB data

# Defining a persistent volume for MongoDB
volumes:
  mongo-data:
